stages:
- name: Build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: dockerchakri/chuck_norris
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./kubernetes.yaml
branch: {}
notification: {}
