stages:
- name: Build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: dockerchakri/chuck_norris
      pushRemote: true
      registry: 127.0.0.1:34679
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./kubernetes.yaml
notification: {}
